// Apple Pay domain verification file.
//
// Apple requires every domain that wants to show Apple Pay to serve a specific
// proof-of-ownership file at this exact URL:
//   https://brikk.store/.well-known/apple-developer-merchantid-domain-association
//
// The file content is generated by Stripe when you register a domain in
//   Dashboard → Settings → Payment Methods → Apple Pay → Add new domain
// You download it from there, paste it into APPLE_PAY_DOMAIN_ASSOCIATION
// below (or set it as an env var), redeploy, then click "Verify" in the
// Stripe Dashboard.
//
// Notes:
//  - The file must be served as plain text (no HTML wrapping, no JSON).
//  - The file content is a single long string Apple-prescribed format.
//  - Once verified, Apple Pay button appears on iOS Safari for eligible cards.

const APPLE_PAY_DOMAIN_ASSOCIATION = process.env.APPLE_PAY_DOMAIN_ASSOCIATION || ''

export async function GET() {
  if (!APPLE_PAY_DOMAIN_ASSOCIATION) {
    // Not configured yet — return 404 so Stripe's verifier knows to fail
    // gracefully and your partner sees "not configured" instead of a half-broken state.
    return new Response('Apple Pay domain association not configured', {
      status: 404,
      headers: { 'Content-Type': 'text/plain' },
    })
  }

  return new Response(APPLE_PAY_DOMAIN_ASSOCIATION, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain',
      // Apple's verifier hits this directly; cache so subsequent checks are quick.
      'Cache-Control': 'public, max-age=3600',
    },
  })
}
